# coding:utf-8
time_out: 200                   # timeout for crawling and storing user info
min_crawl_interal: 10           # min interal of http request
max_crawl_interal: 20           # max interal of http request
excp_interal: 5*60              # time for sleeping when crawling raises exceptions

# TODO set a default value for max_value of crawling
#max_search_page: 50            # max search page for crawling
#max_comment_page: 2000         # max comment page for crawling
#max_repost_page: 2000          # max repost page for crawling
#max_dialogue_page: 2000        # max dialogue page for crawling
max_home_page: 25             # max user home page for crawling
max_retries: 5                 # retry times for crawling

# MySQL
db:
#    host: 10.22.32.29
    host: 127.0.0.1
    port: 3306
    user: root
    password: Zayn9296.
#    user: guest
#    password: guest87654321
    db_name: chunyu_doctor
    db_type: mysql

